### ISSUE TITLE
Issue in example with end block code

### ISSUE THREAD

**Issue by intech** [moleculerjs/moleculer-docgen#4]
https://github.com/moleculerjs/moleculer-docgen/blob/master/examples/README.db.md#test
![Снимок экрана от 2019-08-09 16-06-21](https://user-images.githubusercontent.com/451306/62781051-c2216880-babf-11e9-8ca3-4e26be9ae3e1.png)

**Comment by AndreMaz** [comment]
Thanks @intech. 

@dkuida I think this is related to https://github.com/moleculerjs/moleculer-docgen/pull/3. Can you take a look at this please?
